### ISSUE TITLE
[De]activate scripts not working

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-feedstock#1]
Appears the [de]activate scripts are not working on Linux or Windows. See this [CircleCI log]( https://circleci.com/gh/conda-forge/ipykernel-feedstock/18 ) or this [AppVeyor log]( https://ci.appveyor.com/project/conda-forge/ipykernel-feedstock/build/1.0.13/job/tfsxs88xrpdccwrs#L522 ) for details. @msarahan, any idea what is going on here?

**Comment by jakirkham** [comment]
Seems like this issue should appear on Mac too.

**Comment by jakirkham** [comment]
Have added all of these to the `broken` label and removed the `main`. This should allow the packages to still be inspected. Though they won't be downloaded by default. It will also avoid having new broken packages get uploaded in their place (i.e. as could happen with removal).

**Comment by jakirkham** [comment]
Appears there are only symlinks in `bin`. Guessing we are missing some crucial install step.

**Comment by msarahan** [comment]
I don't know what's going on here, but my best guess is something like:

1) conda-build creates the build environment and activates it.  This makes the symlinks that you are finding.
2) During install (build.sh/bld.bat), something should remove or overwrite those with the actual files.  Is this happening?  Apologies if I am not seeing it, but I think it might be a more manual process than just the python setup.py install.
3) the always_include_files stuff looks OK to me, but that's another area to double-check.

**Comment by jakirkham** [comment]
> 1) conda-build creates the build environment and activates it. This makes the symlinks that you are finding.

That was what I was thinking. Thanks for confirming.

> 2) During install (build.sh/bld.bat), something should remove or overwrite those with the actual files. Is this happening? Apologies if I am not seeing it, but I think it might be a more manual process than just the python setup.py install.

👍 I think this is absolutely right. Was checking for this in the conda repo's [recipe]( https://github.com/conda/conda/blob/83f397d3d596dedc93e0160104dad46c6bfdb7ef/conda.recipe/build.sh ), but am not seeing it there either. Though it looks like this is is a simple matter of copying them in from the [`shell`]( https://github.com/conda/conda/tree/83f397d3d596dedc93e0160104dad46c6bfdb7ef/shell ) directory.

> 3) the always_include_files stuff looks OK to me, but that's another area to double-check.

Ok, will double check this after addressing 2.

**Comment by jakirkham** [comment]
Maybe PR ( https://github.com/conda-forge/conda-feedstock/pull/3 ) will solve this issue.
