### ISSUE TITLE
pull versions 4.7.11 and 4.7.12

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-feedstock#106]
The bug in this conda-build issue https://github.com/conda/conda-build/issues/3735 appears to be related to the conda version. 

Can we mark conda versions 4.7.11 and 4.7.12 as broken for now?

**Comment by beckermr** [comment]
These versions are causing issues on staged recipes that appeared to resolve with 4.7.10.

**Comment by msarahan** [comment]
I would recommend pinning conda on the build workers to <4.7.11a0, rather than pulling 4.7.11 and 4.7.12.  There have been quite a few bug fixes that might be worth keeping for users.

**Comment by beckermr** [comment]
ok - i'll make a PR there

**Comment by msarahan** [comment]
Thanks.  I'm not terribly opposed to pulling it if there are problems for users, too.  I just think it improves things for users, at the unfortunate detriment to builds here.
