### ISSUE TITLE
Conda env entrypoint is missing

### ISSUE THREAD

**Issue by frol** [conda-forge/conda-feedstock#11]
```
$ conda env


CommandNotFoundError: Command Error: error with command 'env'. Command not found: 'env'. Error: Could not locate 'conda-env' env Error: Could not locate 'conda-env'
```

**Comment by jakirkham** [comment]
@kalefranz is there something we need to be doing to keep the `conda-env` command? I agree with @frol that I'm not seeing it.

**Comment by jakirkham** [comment]
I think PR ( https://github.com/conda-forge/conda-feedstock/pull/12 ) should fix it. Do you mind trying it out locally, @frol ?

**Comment by jakirkham** [comment]
Have temporarily pulled the current packages for `conda` version `4.2.11` and `conda-env` version `2.6.0` until we get this sorted out. Should also note that we are seeing another issue with `conda` version `4.2.11` ( https://github.com/conda/conda/issues/3744 ), which is pretty disconcerting.

cc @pelson

**Comment by jakirkham** [comment]
Ultimately fixed by PR ( https://github.com/conda-forge/conda-feedstock/pull/14 ).
