### ISSUE TITLE
site-packages/test_data should be removed or renamed

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-feedstock#116]
maybe rename to `conda_test_data`.

For eg: https://anaconda.org/conda-forge/conda/4.8.3/download/linux-64/conda-4.8.3-py36h9f0ad1d_1.tar.bz2

**Comment by jaimergp** [comment]
I think this is not a problem since 4.11 (check [source tree](https://github.com/conda/conda/tree/4.11.0)). Closing.
