### ISSUE TITLE
OSX:  build having a strange beahaviour ran 6h and was killed

### ISSUE THREAD

**Issue by FabriceSalvaire** [conda-forge/conda-feedstock#118]
Not sure it is the right place ...

It looks like this build  was running forever, I see repeated download logs, any clue ???

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=171225&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c

**Comment by jakirkham** [comment]
Would stick with the issue on the feedstock. This issue tracker is for issues with the `conda` package, which doesn't appear to be the case there.
