### ISSUE TITLE
Master run for conda-4.10.3 failed for Windows

### ISSUE THREAD

**Issue by xhochy** [conda-forge/conda-feedstock#147]
The CI is broken in general for Windows currently but leaving this here as a reminder to retrigger later.

**Comment by jakirkham** [comment]
Looks like this was rerun recently and these are now up. Going to close, but please feel free to reopen if I missed something

<img width="1792" alt="Screen Shot 2021-06-30 at 4 14 40 PM" src="https://user-images.githubusercontent.com/3019665/124042711-49329f00-d9be-11eb-860b-163bd0543e02.png">
