### ISSUE TITLE
conda 4.3?

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/conda-feedstock#16]
I'm actually puzzled about an independent conda-feedstock, shouldn't all conda repos best be managed by the same conda executable? A different channel hopefully doesn't depend on special features of any specific `conda` version?
I'm usually basing my env on conda-forge due to some updates on packages I frequently use, is there any danger in using conda 4.3 from the defaults channel with the current packages of the conda-forge channel?

**Comment by jakirkham** [comment]
It is a possibility, but it also breaks a lot of stuff that we use here. So we would need to proceed with caution. Probably by pinning everything to an old `conda` first. As one example, re-rendering breaks ( https://github.com/SciTools/conda-build-all/issues/76 ). Though other things may break that we haven't tested.

**Comment by michaelaye** [comment]
I see. But that's a building only issue, could that also somehow affect the package management after building?

**Comment by jakirkham** [comment]
Ok, I think I misread this. I thought the question was can we update to `conda` 4.3 in conda-forge. To be clear, the answer was yes, but there are some steps we should take to prevent some known issues from impacting the org as a whole.

A different question is what is the acceptable way to get dependencies from `conda-forge` and use them with `defaults`. The answer to that is the only supported way is to have `conda-forge` take higher priority than `defaults`. We don't support other configurations as that would mean rebuilding the entire stack in that configuration and offering to users in that way, which is not a small ask.

It seems like there are other questions beyond these being asked, but I'm having trouble following them. Could you please rephrase anything that hasn't been answered above?

**Comment by jakirkham** [comment]
I guess one of the other questions could be more generally rephrased as "why did we chose to package things from `defaults` (like `conda`, `python`, etc.)?". The answer is we wanted this to be a completely independent community-driven stack. So we decided to add packages for everything in `defaults` and not in `defaults`

Largely IMHO this is not a detriment as it is easy to update outdated dependencies or make changes that `defaults` is unlikely to support. Though having this outdated `conda` version is a bit of an exception to the rule. That said, it is not impossible to resolve and is merely a matter of testing and patching `conda`, `conda-build-all`, and `conda-smithy` as necessary to make it work.

**Comment by michaelaye** [comment]
Sorry for being imprecise. I understand the motivation behind conda-forge, I think. I was just wondering if it would be possible to decouple the conda package managing part (so the everyday interface to my env management) from `conda-build`, so that the average joe conda user is not afraid to stay behind in conda features, just because I'm using the conda-forge channel. Does that make sense?

**Comment by jakirkham** [comment]
Sorry still lost. Though it may just be me. Are you worried about universal Python packages or something? Maybe an example of the use case would help.

**Comment by michaelaye** [comment]
in hopefully simpler words: as a user, I don't want to wait for `conda-build` problems to be solved for upgrades. Because I'm not building stuff, i wouldn't even know it exists. I am just managing my environments using the `conda` executable, that's what it mean with decouple.
Another way to ask it: Why can't `conda` be upgraded **despite** the `conda-build` problems? Maybe there's an intricate connection that I'm not aware of?

**Comment by msarahan** [comment]
conda has consistently broken its API for the past several versions.  As @jakirkham mentions, this breaks not just conda-build but also other critical tools in the conda-forge stack.  We can pin those tools, and it is possible for us to offer the latest conda at conda-forge without using it in our tool stack.  However, people at conda-forge are rightfully weary from fixing their tooling.  Keeping this feedstock at an earlier version is almost certainly a direct result of fatigue and much-deserved skepticism.  Pinning requires extreme care to ensure that later steps are not accidentally upgrading conda.  There have been, for example, bugs in the past where the ``auto_update_conda`` setting was not respected.

There is no harm in using conda from defaults if you are not building packages.  You can do so just with a one-time ``conda update -c defaults conda`` and ``conda conda --set auto_update_conda false`` to avoid automatic updates.  I am in favor of keeping the conda-feedstock here at the latest known-compatible version to minimize the cognitive load of the people like @jakirkham who spend lots of time trying to keep this ship running.

As conda-build is reaching a good point of maturity, I'll be working on conda more soon, and hoping to provide a stable programmatic API that will finally mitigate these problems and allow people to update conda with less concern.  Until then, please install from defaults if you must have the latest.

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/conda-feedstock/pull/18

**Comment by dartdog** [comment]
Have ended up deleting and re-installing anaconda to get the base version updated to Python3.6 (vs 3.5) now have to recreate all my env's. py27, py35. And add my somewhat complex set of packages (Tensorflow-gpu, Keras etc.... Not pretty.. Also discovering a number of things not readily available in 3.6 that are in 3.5.. Conda NB extensions for a start..

**Comment by michaelaye** [comment]
jupyter_contrib_nbextensions are **ONLY* on conda-forge (unless they have a different name on the defaults channel?), but nb_conda_kernels are on both, also for py3.6.

**Comment by dartdog** [comment]
The clarification is a big help! Thanks

**Comment by slavoutich** [comment]
Seems like I have fixed simple CI issue, that caused appveyor to fail. Can we proceed with fixing this? 4.3 is really needed, they have fixed a lot of bugs there, especially with read-only root environment.
