### ISSUE TITLE
Add a test outside of conda build step to test the package

### ISSUE THREAD

**Issue by janschulz** [conda-forge/conda-feedstock#2]
Basically the same as https://github.com/conda-forge/python-feedstock/issues/22

-> Test that this package is actually fit for duty and does not potentially screws up a users main conda installation

Probably needs changes in conda-smithy...

**Comment by jakirkham** [comment]
Was actually just thinking about this again today. Thanks for raising this.

Could see this being useful for `conda`, `conda-build`, and `anaconda-client` as well. Though there are probably some other cases worth thinking about too.

**Comment by jakirkham** [comment]
Could we actually raise this with `conda-smithy` too? It seems like there will need to be some changes with it to accommodate this behavior generally.

**Comment by janschulz** [comment]
@jakirkham done, here: https://github.com/conda-forge/conda-smithy/issues/253

**Comment by jakirkham** [comment]
I think we may be able to address the underlying concerns here with PR ( https://github.com/conda-forge/conda-feedstock/pull/26 ). This doesn't actually test outside of `conda-build`'s `test` step. It instead tests inside that step, but does a bit of work to make it appear like a normal `root` environment with `conda` installed. By doing this, I think it will be easier to cleanup and easier for people to test locally, which seems desirable.
