### ISSUE TITLE
Fix electrode

### ISSUE THREAD

**Issue by vladislavivanistsev** [conda-forge/conda-feedstock#227]
### Comment:

Could you please add fix electrode by adding the following?

    -D PKG_ELECTRODE=yes \
    -D PKG_KSPACE=yes \
    -D USE_INTERNAL_LINALG=ON \

**Comment by jakirkham** [comment]
Could you please add more context? Am not sure what this is referring to

**Comment by mbargull** [comment]
Whatever this is supposed to request, this is definitely out of scope here.

**Comment by jakirkham** [comment]
I'm guessing it was intended for a different feedstock, but didn't have enough to go on from the report to transfer it to the right place
