### ISSUE TITLE
Activate scripts missing in windows 4.3.21 package

### ISSUE THREAD

**Issue by adament** [conda-forge/conda-feedstock#24]
In the Python 2.7, 3.6 win-64 versions and 3.6 win-32 versions of the 4.3.21 package on https://anaconda.org/conda-forge/conda/files the activate and deactivate scripts are missing.

I have not checked in other Windows packages but they do seem to be in the Linux packages.

**Comment by adament** [comment]
I am sorry for closing and reopening the issue, that was me inadvertently hitting the close button.

**Comment by jakirkham** [comment]
NP. I see. That would probably explain some of the issues we have run into with it on conda-forge. Would you like to propose a fix?

xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/72

**Comment by jakirkham** [comment]
Also this [line]( https://ci.appveyor.com/project/conda-forge/conda-feedstock/build/1.0.57/job/u3914uahfeg8xq1x#L985 ) in the log seems relevant. It looks like these files may now have a `.bat` extension. So the symlinks should take this into account. Not sure if the symlinked files should also have this extension or not.

**Comment by jakirkham** [comment]
Seems there are a few other things that were missed to like [`conda-init`]( https://ci.appveyor.com/project/conda-forge/conda-feedstock/build/1.0.57/job/u3914uahfeg8xq1x#L974 ) and [`conda.fish`]( https://ci.appveyor.com/project/conda-forge/conda-feedstock/build/1.0.57/job/u3914uahfeg8xq1x#L970 ). Probably need to sprinkle many more `if errorlevel 1 exit 1` lines throughout the `bld.bat`.

**Comment by jakirkham** [comment]
After doing a deep dive in the `conda` codebase it looks like basically everything got revamped. We no longer need many of the hacks that were in the `conda` 4.2 recipe as that logic got moved into `setup.py` and then into `conda` proper.

**Comment by jakirkham** [comment]
Attempting to fix in PR ( https://github.com/conda-forge/conda-feedstock/pull/25 ). The more eyes the better.
