### ISSUE TITLE
conda 24.11.0 osx-64 for Python 3.12 failing due to downstream smithy tests

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-feedstock#245]
It keeps [failing](https://github.com/conda-forge/conda-feedstock/runs/33509271997) because the linter complains that the `isuruf` user doesn't exist. I've rerun this a couple times and it fails consistently. Not sure if it's a temporary API problem but I'll try again tomorrow. Otherwise we'll need to disable the tests for that build temporarily; everything else is passing 🤷

**Comment by h-vetinari** [comment]
It's a flaky error that should go away with restarts. See https://github.com/conda-forge/conda-smithy/issues/2164

**Comment by jakirkham** [comment]
Tried [a restart]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1090720&view=logs&j=11c9cf2f-7274-5168-70a2-8cf98a36f64c&t=7e5c6908-fdb6-50c3-2341-799738165ef6 )

**Comment by jaimergp** [comment]
Took five attempts but it passed.

**Comment by h-vetinari** [comment]
Matt [disabled](https://github.com/conda-forge/conda-smithy-feedstock/pull/336) that flaky test in the `conda-smithy` feedstock now, meaning it will not be attempted in `downstreams:` runs anymore.

**Comment by beckermr** [comment]
Make sure the right version and build of smithy is pulled in maybe?

**Comment by h-vetinari** [comment]
> Make sure the right version and build of smithy is pulled in maybe?

There shouldn't be any constraints here that force older conda-smithy. The failing runs were all with
```
    conda-smithy:                         3.44.7-unix_pyhd81877a_2       local  
```
which was the latest at the time (and before https://github.com/conda-forge/conda-smithy-feedstock/pull/336). They were simply very unlucky (perhaps some circumstances conspired to make it more likely on that particular combination). The passing run was with
```
    conda-smithy:                         3.44.8-unix_pyhd81877a_0       local  
```
and thus after the flaky test was disabled.
