### ISSUE TITLE
Do not build 4.3.28

### ISSUE THREAD

**Issue by msarahan** [conda-forge/conda-feedstock#33]
This release caused lots of issues, detailed at https://github.com/conda/conda/issues/6096

Please do not package it - and please close any PRs that do that update.

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by kalefranz** [comment]
conda 4.3.29 is available

**Comment by kalefranz** [comment]
I believe this issue can be closed.  #34 should be merged asap
