### ISSUE TITLE
minor version behind defaults channel?

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/conda-feedstock#8]
I was just wondering why the conda-forge conda is on 4.1.x while the defaults channel is using conda 4.2.x? Usually the conda-forge products are more `daring` (for the lack of a better word), is there a known issue with conda 4.2.x?

**Comment by jakirkham** [comment]
Mainly because `conda-env` vanishes as it is absorbed into `conda` in `4.2.x`. Please see the linked PRs for details.

xref: https://github.com/conda-forge/conda-env-feedstock/pull/1
xref: https://github.com/conda-forge/conda-feedstock/pull/6

**Comment by michaelaye** [comment]
Thanks!
